### ISSUE TITLE
Plugins dependencies

### ISSUE THREAD

**Issue by ppiotrow** [technipelago/gr8crm-demo-app#1]
Hi. I've installed grails 2.2.4. After cloning and compiling your project it can't resolve plugins dependencies. Is it some lack of repository configuration?

```
| Error Failed to resolve dependencies (Set log level to 'warn' in BuildConfig.groovy for more information):

- org.grails.plugins:jquery:1.10.2
- org.grails.plugins:resources:1.2.7
- org.grails.plugins:twitter-bootstrap:2.3.2
- org.grails.plugins:less-resources:1.3.3.2
- org.grails.plugins:database-migration:1.3.6
- org.grails.plugins:cache:1.1.1
- org.grails.plugins:greenmail:1.3.4
- org.grails.plugins:mail:1.0.7
- org.grails.plugins:decorator-markdown:0.4
- org.grails.plugins:crm-security-shiro:2.0.0
- org.grails.plugins:crm-i18n:2.0.0
- org.grails.plugins:crm-contact-ui:2.0.0
- org.grails.plugins:crm-task-ui:2.0.0
- org.grails.plugins:crm-content-ui:2.0.1
```

**Comment by goeh** [comment]
That's all dependencies. Sounds like a temporary outage at grailsCentral repository or lost internet connection. Can you try "grails compile" again and see if it still fails?

**Comment by ppiotrow** [comment]
I'll try this at home. It might be caused by some kind of proxy in my
office.
3 mar 2015 16:05 "Goran Ehrsson" notifications@github.com napisał(a):

**Comment by ppiotrow** [comment]
Hi, in my private computer after steps

```
curl -s get.gvmtool.net | bash
source "/home/myaccount/.gvm/bin/gvm-init.sh"
gvm install grails 2.2.4
git clone https://github.com/technipelago/gr8crm-demo-app
cd gr8crm-demo-app
grails compile
```

I have the same error about plugins dependencies. Maybe it's an error in grails 2.2.4?

**Comment by goeh** [comment]
I found the following on SO http://stackoverflow.com/questions/28836824/grails-2-2-x-unresolved-dependencies-without-any-changes-to-previously-working-b

Add `mavenRepo "http://repo.grails.org/grails/repo/"` to BuildConfig.groovy

I guess it's related to codehaus repo shutting down last week.

**Comment by goeh** [comment]
I have added the repo to BuildConfig.groovy now. Please pull the changes to gr8crm-demo-app and try to compile again.

**Comment by goeh** [comment]
I have been developing with Grails 2.2.4 a lot this week and did not notice this problem. It's pure luck that I already had all dependencies download on my laptop.

I created a fresh docker image to confirm the problem.

Thanks ppiotrow for reporting this issue.

**Comment by ppiotrow** [comment]
Thanks, it solved my problems.
