### ISSUE TITLE
Does not work with java 6 and java 8

### ISSUE THREAD

**Issue by aberbenni** [technipelago/gr8crm-demo-app#2]
With java 6 I have a: 
UnsupportedClassVersionError: com/google/zxing/qrcode/QRCodeWriter

With java 8:
  Cannot invoke method getAt() on null object (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.lang.NullPointerException: Cannot invoke method getAt() on null object
    at grails.util.BuildSettings.configureDependencyManager(BuildSettings.groovy:1259)
(This is a Grails 2.2.x problem)

I think this should be upgraded to grails 2.3.x or more recent.

**Comment by goeh** [comment]
The demo application is now compatible with Grails 2.4.4. 

GR8 CRM plugins with version number 2.4.0 and higher are compatible with Grails 2.4.4.
The following plugins has been upgraded:
- crm-contact-ui
- crm-content-ui
- crm-task-ui
- crm-security
- crm-security-shiro
- crm-ui-bootstrap
- crm-notes
- crm-tags
- crm-i18n
- crm-feature
- crm-core

All plugins are compiled with JDK7. The demo application runs fine with Java 7 or Java 8.

**Comment by aberbenni** [comment]
GR8 CRM plugins with version number 2.4.0 are no more compatible with grails < 2.4.x (eg: 2.2.x and 2.3.x)
Here is an exception I have: CrmSecurityService.groovy: 26: unable to resolve class grails.compiler.GrailsCompileStatic

Is there a version compatible with grails 2.3.x?

**Comment by goeh** [comment]
I'm sorry but I don't have time or resources to do a 2.3 version also. There are too many changes between Grails version 2.2, 2.3 and 2.4. GR8 CRM plugin versions 2.0.x are compatible with Grails 2.2.x and GR8 CRM plugin versions 2.4.x are compatible with Grails 2.4.x.

If someone want to do Grails 2.3 versions I welcome contributions. Maybe branch from _master_ (Grails 2.4) is easier, but I'm not sure. The _grails-2.2.x_ branch contains the Grails 2.2.4 compatible version.
