### ISSUE TITLE
Build is successful but failed to start with grails 2.4.4 on ubuntu

### ISSUE THREAD

**Issue by ejaz-ahmed** [technipelago/gr8crm-demo-app#3]
Hi,

I just wanted to experiment this app on my machine with grails 2.4.4 on Ubuntu 14.04 and Java 1.7 . I have come across following issue. Although there were many other database related errors but those are not causing any problem as it is common with hibernate to throw such errors. One useful error message is /tmpgr8crm path which can't be created by this app. I have grepped for this text but could not found in my app directory. Looks like some other gr8crm plugin needs this path. Any suggestions from your side?

| Error 2015-04-03 20:05:43,720 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Disk store path can't be created: /tmpgr8crm
Message: Disk store path can't be created: /tmpgr8crm
    Line | Method
->>  141 | resolveAndLockIfNeeded in net.sf.ehcache.DiskStorePathManager

---

|    262 | getFile                in     ''
|    251 | getFile . . . . . . .  in     ''
|    127 | <init>                 in net.sf.ehcache.store.disk.DiskStorageFactory
|    154 | create . . . . . . . . in net.sf.ehcache.store.disk.DiskStore
|    182 | createCacheStore       in     ''
|   1199 | initialise . . . . . . in net.sf.ehcache.Cache
|   1370 | initializeEhcache      in net.sf.ehcache.CacheManager
|   1436 | addCacheNoCheck . . .  in     ''
|    832 | addConfiguredCaches    in     ''
|    500 | doInit . . . . . . . . in     ''
|    395 | init                   in     ''
|    184 | rebuild . . . . . . .  in grails.plugin.cache.ehcache.GrailsEhCacheManagerFactoryBean$ReloadableCacheManager
|     63 | reload                 in grails.plugin.cache.ehcache.EhcacheConfigLoader
|     42 | reload . . . . . . . . in grails.plugin.cache.ConfigLoader
|    202 | reloadCaches           in CacheGrailsPlugin
|    158 | doCall . . . . . . . . in CacheGrailsPlugin$_closure3
|    262 | run                    in java.util.concurrent.FutureTask
|   1145 | runWorker . . . . . .  in java.util.concurrent.ThreadPoolExecutor
|    615 | run                    in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . . . . . . .  in java.lang.Thread
| Error 2015-04-03 20:05:43,972 [Thread-12] ERROR hbm2ddl.SchemaExport  - HHH000231: Schema export unsuccessful
Message: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-176]
    Line | Method
->>  344 | getJdbcSQLException in org.h2.message.DbException

---

|    178 | get                 in     ''
|    154 | get . . . . . . . . in     ''
|    143 | get                 in     ''
|   1468 | checkClosed . . . . in org.h2.jdbc.JdbcConnection
|   1443 | checkClosed         in     ''
|    446 | getAutoCommit . . . in     ''
^    745 | run                 in java.lang.Thread
| Error Forked Grails VM exited with error

**Comment by goeh** [comment]
It was the configuration of EHCache diskstore path that expected java.io.tmpdir to include a trailing slash. But in your case it does not have a trailing slash. I added a slash as a quick fix so you can continue testing. But a better solution should be implemented that can handle java.io.tmpdir with or without trailing slash. Pull requests are welcome.

Please pull my latest changes on master and try again.

https://github.com/technipelago/gr8crm-demo-app/blob/master/grails-app/conf/ApplicationCacheConfig.groovy#L15

**Comment by goeh** [comment]
Have you tried the patch? Can I close the issue?

**Comment by ejaz-ahmed** [comment]
Yes. It is working. Just forgot to inform you timely. Closing this now.
